---
http_interactions:
- request:
    method: get
    uri: https://user:pass@customer-webtools-api.internode.on.net/api/v1.5/1
    body:
      encoding: UTF-8
      string: ''
    headers:
      User-Agent:
      - HTTPClient/1.0 (2.6.0.1, ruby 2.2.2 (2015-04-13))
      Accept:
      - "*/*"
      Date:
      - Fri, 07 Aug 2015 11:49:22 GMT
      Authorization:
      - Basic dXNlcjpwYXNz
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Fri, 07 Aug 2015 11:49:22 GMT
      Server:
      - Apache
      Pragma:
      - no-cache, no-cache, no-cache
      Connection:
      - close
      Transfer-Encoding:
      - chunked
      Content-Type:
      - application/xml
    body:
      encoding: UTF-8
      string: |
        <?xml version="1.0" encoding="UTF-8"?>
        <internode><api><service type="Personal_ADSL">1</service><resources count="3"><resource type="history" href="/api/v1.5/1/history">history</resource><resource type="usage" href="/api/v1.5/1/usage">usage</resource><resource type="service" href="/api/v1.5/1/service">service</resource></resources></api></internode>
    http_version: 
  recorded_at: Fri, 07 Aug 2015 11:49:22 GMT
recorded_with: VCR 2.9.3
